-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-11-16 11:51:53 GMT-05:00
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

DROP TABLE admin_account CASCADE CONSTRAINTS;
DROP TABLE condition CASCADE CONSTRAINTS;
DROP TABLE contribution CASCADE CONSTRAINTS;
DROP TABLE deletion_request CASCADE CONSTRAINTS;
DROP TABLE eligibilty CASCADE CONSTRAINTS;
DROP TABLE id_request CASCADE CONSTRAINTS;
DROP TABLE membership CASCADE CONSTRAINTS;
DROP TABLE membership_request CASCADE CONSTRAINTS;
DROP TABLE plan CASCADE CONSTRAINTS;
DROP TABLE plan_request CASCADE CONSTRAINTS;
DROP TABLE provider CASCADE CONSTRAINTS;
DROP TABLE sponsor_account CASCADE CONSTRAINTS;
DROP TABLE transfer_request CASCADE CONSTRAINTS;



CREATE TABLE admin_account (
    adminid   CHAR(10) NOT NULL,
    email     VARCHAR2(100),
    password  VARCHAR2(100),
    firstname VARCHAR2(100),
    lastname  VARCHAR2(100)
);

ALTER TABLE admin_account ADD CONSTRAINT admin_account_pk PRIMARY KEY ( adminid );



CREATE TABLE condition (
    eligibilty_eligibilityid CHAR(10) NOT NULL,
    threshhold               VARCHAR2(100),
    reason                   VARCHAR2(100),
    description              VARCHAR2(100)
);

ALTER TABLE condition ADD CONSTRAINT condition_pk PRIMARY KEY ( eligibilty_eligibilityid );



CREATE TABLE contribution (
    paymentid                 CHAR(10) NOT NULL,
    membership_memberid       CHAR(10) NOT NULL,
    totalamount               VARCHAR2(10),
    contributionrate          VARCHAR2(10),
    datereceived              DATE,
    sponsor_account_sponsorid CHAR(10) NOT NULL
);


ALTER TABLE contribution ADD CONSTRAINT contribution_pk PRIMARY KEY ( paymentid,
                                                                      membership_memberid );


CREATE TABLE deletion_request (
    requestid           CHAR(10) NOT NULL,
    membership_memberid CHAR(10) NOT NULL,
    reason              VARCHAR2(100),
    description         VARCHAR2(100),
    requestdate         DATE
);

CREATE UNIQUE INDEX deletion_request__idx ON
    deletion_request (
        membership_memberid
    ASC );

ALTER TABLE deletion_request ADD CONSTRAINT deletion_request_pk PRIMARY KEY ( requestid );


CREATE TABLE eligibilty (
    eligibilityid CHAR(10) NOT NULL,
    plan_planid   CHAR(10) NOT NULL,
    type          VARCHAR2(100),
    description   VARCHAR2(100)
);

CREATE UNIQUE INDEX eligibilty__idx ON
    eligibilty (
        plan_planid
    ASC );

ALTER TABLE eligibilty ADD CONSTRAINT eligibilty_pk PRIMARY KEY ( eligibilityid );



CREATE TABLE id_request (
    idrequestid               CHAR(10) NOT NULL,
    admin_account_adminid     CHAR(10) NOT NULL,
    reason                    VARCHAR2(100),
    requestdate               DATE,
    sponsor_account_sponsorid CHAR(10) NOT NULL
);

CREATE UNIQUE INDEX id_request__idx ON
    id_request (
        sponsor_account_sponsorid
    ASC );

ALTER TABLE id_request ADD CONSTRAINT id_request_pk PRIMARY KEY ( idrequestid );



CREATE TABLE membership (
    memberid    CHAR(10) NOT NULL,
    email       VARCHAR2(100),
    firstname   VARCHAR2(100),
    lastname    VARCHAR2(100),
    password    VARCHAR2(100),
    phonenumber CHAR(10)
);

ALTER TABLE membership ADD CONSTRAINT membership_pk PRIMARY KEY ( memberid );



CREATE TABLE membership_request (
    memrequestid              CHAR(10) NOT NULL,
    membership_memberid       CHAR(10) NOT NULL,
    sponsor_account_sponsorid CHAR(10) NOT NULL,
    description               VARCHAR2(100),
    requestdate               DATE
);

ALTER TABLE membership_request ADD CONSTRAINT membership_request_pk PRIMARY KEY ( memrequestid,
                                                                                  membership_memberid );


CREATE TABLE plan (
    planid              CHAR(10) NOT NULL,
    provider_providerid CHAR(10) NOT NULL,
    type                VARCHAR2(100),
    reward              VARCHAR2(10)
);

ALTER TABLE plan ADD CONSTRAINT plan_pk PRIMARY KEY ( planid );


CREATE TABLE plan_request (
    planrequestid             CHAR(10) NOT NULL,
    membership_memberid       CHAR(10) NOT NULL,
    plan_planid               CHAR(10) NOT NULL,
    reason                    VARCHAR2(100),
    description               VARCHAR2(100),
    requestdate               DATE,
    sponsor_account_sponsorid CHAR(10) NOT NULL
);

ALTER TABLE plan_request ADD CONSTRAINT plan_request_pk PRIMARY KEY ( planrequestid,
                                                                      membership_memberid );


CREATE TABLE provider (
    providerid   CHAR(10) NOT NULL,
    providername VARCHAR2(100),
    providertype VARCHAR2(100)
);

ALTER TABLE provider ADD CONSTRAINT provider_pk PRIMARY KEY ( providerid );



CREATE TABLE sponsor_account (
    sponsorid              CHAR(10) NOT NULL,
    password               VARCHAR2(100),
    companyllc             VARCHAR2(100),
    companyname            VARCHAR2(100)
    );

/*CREATE UNIQUE INDEX sponsor_account__idx ON
    sponsor_account (
        id_request_idrequestid
    ASC );*/

ALTER TABLE sponsor_account ADD CONSTRAINT sponsor_account_pk PRIMARY KEY ( sponsorid );



CREATE TABLE transfer_request (
    tranrequestid             CHAR(10) NOT NULL,
    membership_memberid       CHAR(10) NOT NULL,
    sponsor_account_sponsorid CHAR(10) NOT NULL,
    reason                    VARCHAR2(100),
    requestdate               DATE
);

ALTER TABLE transfer_request ADD CONSTRAINT transfer_request_pk PRIMARY KEY ( tranrequestid,
                                                                              membership_memberid );

ALTER TABLE condition
    ADD CONSTRAINT condition_eligibilty_fk FOREIGN KEY ( eligibilty_eligibilityid )
        REFERENCES eligibilty ( eligibilityid );

ALTER TABLE contribution
    ADD CONSTRAINT contribution_membership_fk FOREIGN KEY ( membership_memberid )
        REFERENCES membership ( memberid );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE contribution
    ADD CONSTRAINT contribution_sponsor_account_fk FOREIGN KEY ( sponsor_account_sponsorid )
        REFERENCES sponsor_account ( sponsorid );

ALTER TABLE deletion_request
    ADD CONSTRAINT deletion_request_membership_fk FOREIGN KEY ( membership_memberid )
        REFERENCES membership ( memberid );

ALTER TABLE eligibilty
    ADD CONSTRAINT eligibilty_plan_fk FOREIGN KEY ( plan_planid )
        REFERENCES plan ( planid );

ALTER TABLE id_request
    ADD CONSTRAINT id_request_admin_account_fk FOREIGN KEY ( admin_account_adminid )
        REFERENCES admin_account ( adminid );

ALTER TABLE id_request
    ADD CONSTRAINT id_request_sponsor_account_fk FOREIGN KEY ( sponsor_account_sponsorid )
        REFERENCES sponsor_account ( sponsorid );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE membership_request
    ADD CONSTRAINT membership_request_membership_fk FOREIGN KEY ( membership_memberid )
        REFERENCES membership ( memberid );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE membership_request
    ADD CONSTRAINT membership_request_sponsor_account_fk FOREIGN KEY ( sponsor_account_sponsorid )
        REFERENCES sponsor_account ( sponsorid );

ALTER TABLE plan
    ADD CONSTRAINT plan_provider_fk FOREIGN KEY ( provider_providerid )
        REFERENCES provider ( providerid );

ALTER TABLE plan_request
    ADD CONSTRAINT plan_request_membership_fk FOREIGN KEY ( membership_memberid )
        REFERENCES membership ( memberid );

ALTER TABLE plan_request
    ADD CONSTRAINT plan_request_plan_fk FOREIGN KEY ( plan_planid )
        REFERENCES plan ( planid );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE plan_request
    ADD CONSTRAINT plan_request_sponsor_account_fk FOREIGN KEY ( sponsor_account_sponsorid )
        REFERENCES sponsor_account ( sponsorid );

ALTER TABLE transfer_request
    ADD CONSTRAINT transfer_request_membership_fk FOREIGN KEY ( membership_memberid )
        REFERENCES membership ( memberid );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE transfer_request
    ADD CONSTRAINT transfer_request_sponsor_account_fk FOREIGN KEY ( sponsor_account_sponsorid )
        REFERENCES sponsor_account ( sponsorid );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             4
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   5
-- WARNINGS                                 0
